author: meta1203
database: true
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.meta1203.plugins.metaport.Metaport
name: MetaPort
startup: startup
url: http://www.metaserve.net/
version: '1.0'
